fix(pkg): require `node` `^12.20 || >= 14.13`
`npx` / `node` in prior versions fail with:

```sh
$ npx buschtoens
npx: installed 88 in 3.063s
file:///Users/jan/.npm/_npx/22231/lib/node_modules/buschtoens/ui.js:1
import { Box, Text, Spacer, Newline } from 'ink';
         ^^^
SyntaxError: The requested module 'ink' does not provide an export named 'Box'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```

https://github.com/nodejs/node/pull/35249